version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.shuaipeng.local`)"
  gin-demo:
    image: niaoshuai/gin-demo
    labels:
      - "traefik.http.routers.gin-demo.rule=Host(`gin-demo.shuaipeng.local`)"
    expose:
      - 80
